### ISSUE TITLE
Error Linking Google Docs/Drive

### ISSUE THREAD

**Issue by sg000** [tapnair/FusionSheeter#3]
When trying to connect/authorize Google Docs I get the following error in Fusion360. And unlike the YouTube demo, Google doesn't like the app and thinks its unsafe, which isn't too surprising, but I allowed it anyways.

![image](https://user-images.githubusercontent.com/30939913/75255935-bb82e600-57b0-11ea-8779-1da8fde66fd5.png)

**Comment by sg000** [comment]
Import to pull down the latest branch. I used the link in the description and that must download an old version. Noticed there were commits 19 days ago, found that branch and downloaded. Problem is not a problem.

**Comment by tapnair** [comment]
Oh wow thanks for that catch.  I'll update the link.  were you refering to the link in the YouTube description?

**Comment by tapnair** [comment]
mI see, in the readme.  It is fixed.
