### ISSUE TITLE
Export Filename

### ISSUE THREAD

**Issue by sg000** [tapnair/FusionSheeter#5]
Love the tool. Thank you!  Less issue and more feature. But the export option, it would be great if it utilized the PartNumber for each line in the spreadsheet. Name them accordingly, or somehow use the size, rather than just 1, 2, 3.

Also, don't know if its possible to set default export file type, as I only export STL.

Still awesome, though, thanks again.

**Comment by tapnair** [comment]
Ahh yes, thats one I've been thinking about.  Option for output file name to be name_X, description, number, or custom.
I have an idea on it.  I'll try to make this change soon.

**Comment by tapnair** [comment]
I have added this capability to export local files and save fusion designs commands
